-- Supabase (Postgres) setup for real "How Others Chose" percentages.
-- Run this in Supabase SQL Editor.

-- 1) Votes table
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  dilemma_id int not null,
  choice text not null check (choice in ('a','b')),
  created_at timestamptz not null default now()
);

-- 2) Enable RLS
alter table public.votes enable row level security;

-- 3) Policy: allow anonymous inserts (for a public voting app)
drop policy if exists "anon insert votes" on public.votes;
create policy "anon insert votes"
on public.votes
for insert
to anon
with check (true);

-- 4) Stats RPC (returns counts for A/B for one dilemma)
-- Marked SECURITY DEFINER so it can read votes even with RLS enabled.
create or replace function public.get_vote_stats(dilemma_id int)
returns table(choice text, count bigint)
language sql
security definer
set search_path = public
as $$
  select v.choice, count(*)::bigint
  from public.votes v
  where v.dilemma_id = get_vote_stats.dilemma_id
  group by v.choice
$$;

revoke all on function public.get_vote_stats(int) from public;
grant execute on function public.get_vote_stats(int) to anon;

