-- Supabase (Postgres) setup for real "How Others Chose" percentages.
-- Run this in Supabase SQL Editor.

-- 1) Votes table
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  dilemma_id int not null,
  choice text not null check (choice in ('a','b')),
  created_at timestamptz not null default now()
);

-- 2) Enable RLS
alter table public.votes enable row level security;

-- 3) Policy: allow anonymous inserts (for a public voting app)
drop policy if exists "anon insert votes" on public.votes;
create policy "anon insert votes"
on public.votes
for insert
to anon
with check (true);

-- 4) Stats RPC (returns counts for A/B for one dilemma)
-- Marked SECURITY DEFINER so it can read votes even with RLS enabled.
create or replace function public.get_vote_stats(dilemma_id int)
returns table(choice text, count bigint)
language sql
security definer
set search_path = public
as $$
  select v.choice, count(*)::bigint
  from public.votes v
  where v.dilemma_id = get_vote_stats.dilemma_id
  group by v.choice
$$;

revoke all on function public.get_vote_stats(int) from public;
grant execute on function public.get_vote_stats(int) to anon;

-- 5) User feedback (anonymous insert; read in Dashboard / SQL)
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  locale text
);

alter table public.feedback enable row level security;

drop policy if exists "anon insert feedback" on public.feedback;
create policy "anon insert feedback"
on public.feedback
for insert
to anon
with check (true);

-- Some Supabase projects do not auto-grant table privileges to anon for new tables.
-- Make insert explicit; keep reads disabled for anon.
revoke all on table public.feedback from anon;
grant insert on table public.feedback to anon;

-- 6) AI usage quota (per device per day)
create table if not exists public.ai_usage_daily (
  device_id text not null,
  day date not null,
  count int not null default 0 check (count >= 0),
  updated_at timestamptz not null default now(),
  primary key (device_id, day)
);

alter table public.ai_usage_daily enable row level security;

-- No client-side access required; the Edge Function updates this table using service role.
revoke all on table public.ai_usage_daily from anon;

-- Atomic quota increment (1 call from Edge Function)
-- NOTE: Use positional args ($1/$2) to avoid ambiguity with column names.
create or replace function public.increment_ai_usage_daily(device_id text, limit_per_day int default 50)
returns table(allowed boolean, count int, remaining int)
language plpgsql
security definer
set search_path = public
as $$
declare
  d date := (now() at time zone 'utc')::date;
  new_count int;
begin
  -- Try to insert a new row with count=1, but only update if below limit.
  insert into public.ai_usage_daily(device_id, day, count)
  values ($1, d, 1)
  on conflict (device_id, day) do update
    set count = public.ai_usage_daily.count + 1,
        updated_at = now()
    where public.ai_usage_daily.count < $2
  returning public.ai_usage_daily.count into new_count;

  if new_count is null then
    select public.ai_usage_daily.count into new_count
    from public.ai_usage_daily
    where public.ai_usage_daily.device_id = $1
      and public.ai_usage_daily.day = d;
    return query select false, coalesce(new_count, $2), 0;
  end if;

  return query select true, new_count, greatest(0, $2 - new_count);
end;
$$;

revoke all on function public.increment_ai_usage_daily(text, int) from public;
grant execute on function public.increment_ai_usage_daily(text, int) to anon;

-- Atomic quota increment v2 (renamed params to avoid ambiguity in some Postgres setups)
create or replace function public.increment_ai_usage_daily_v2(p_device_id text, p_limit_per_day int default 50)
returns table(allowed boolean, count int, remaining int)
language plpgsql
security definer
set search_path = public
as $$
declare
  d date := (now() at time zone 'utc')::date;
  new_count int;
begin
  insert into public.ai_usage_daily(device_id, day, count)
  values (p_device_id, d, 1)
  on conflict (device_id, day) do update
    set count = public.ai_usage_daily.count + 1,
        updated_at = now()
    where public.ai_usage_daily.count < p_limit_per_day
  returning public.ai_usage_daily.count into new_count;

  if new_count is null then
    select public.ai_usage_daily.count into new_count
    from public.ai_usage_daily
    where public.ai_usage_daily.device_id = p_device_id
      and public.ai_usage_daily.day = d;

    return query select false, coalesce(new_count, p_limit_per_day), 0;
  end if;

  return query select true, new_count, greatest(0, p_limit_per_day - new_count);
end;
$$;

revoke all on function public.increment_ai_usage_daily_v2(text, int) from public;
grant execute on function public.increment_ai_usage_daily_v2(text, int) to anon;

-- 7) Bookmarks (anonymous, device-scoped via X-Device-Id header)
-- Client must send header: X-Device-Id: <dd_device_id>
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  device_id text not null,
  item_type text not null check (item_type in ('dilemma','quote','concept','book','video')),
  item_key text not null,
  dilemma_id int,
  locale text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (device_id, item_type, item_key)
);

create index if not exists bookmarks_device_id_idx on public.bookmarks (device_id);
create index if not exists bookmarks_device_type_idx on public.bookmarks (device_id, item_type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_bookmarks_updated_at on public.bookmarks;
create trigger set_bookmarks_updated_at
before update on public.bookmarks
for each row
execute function public.set_updated_at();

alter table public.bookmarks enable row level security;

-- Device id is provided as a request header. PostgREST exposes request headers via GUC:
-- current_setting('request.headers', true) -> JSON
create or replace function public.request_device_id()
returns text
language sql
stable
as $$
  select nullif(trim((current_setting('request.headers', true)::json ->> 'x-device-id')::text), '');
$$;

drop policy if exists "device select bookmarks" on public.bookmarks;
create policy "device select bookmarks"
on public.bookmarks
for select
to anon
using (device_id = public.request_device_id());

drop policy if exists "device insert bookmarks" on public.bookmarks;
create policy "device insert bookmarks"
on public.bookmarks
for insert
to anon
with check (device_id = public.request_device_id());

drop policy if exists "device update bookmarks" on public.bookmarks;
create policy "device update bookmarks"
on public.bookmarks
for update
to anon
using (device_id = public.request_device_id())
with check (device_id = public.request_device_id());

drop policy if exists "device delete bookmarks" on public.bookmarks;
create policy "device delete bookmarks"
on public.bookmarks
for delete
to anon
using (device_id = public.request_device_id());

revoke all on table public.bookmarks from anon;
grant select, insert, update, delete on table public.bookmarks to anon;

-- 8) Forum (posts, comments, A/B votes, reactions)
-- Full migration: supabase/migrations/20260517120000_forum.sql
-- Sample dilemmas stay in FORUM_SAMPLE_POSTS (JS); user posts persist in forum_posts.
-- Client sends X-Device-Id (same as bookmarks) for writes.

create table if not exists public.forum_posts (
  id text primary key,
  device_id text not null,
  author_display text not null default 'You',
  avatar_id text,
  title text not null check (char_length(trim(title)) > 0 and char_length(title) <= 200),
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  option_a text not null check (char_length(trim(option_a)) > 0 and char_length(option_a) <= 200),
  option_b text not null check (char_length(trim(option_b)) > 0 and char_length(option_b) <= 200),
  concepts text[] not null default '{}'::text[],
  locale text,
  posted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.forum_post_votes (
  id bigint generated always as identity primary key,
  post_id text not null,
  device_id text not null,
  choice text not null check (choice in ('a', 'b')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, device_id)
);

create table if not exists public.forum_comments (
  id bigint generated always as identity primary key,
  post_id text not null,
  device_id text not null,
  author_display text not null default 'You',
  avatar_id text,
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  reply_to_comment_id bigint references public.forum_comments (id) on delete set null,
  posted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.forum_post_reactions (
  id bigint generated always as identity primary key,
  post_id text not null,
  device_id text not null,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, device_id)
);

create table if not exists public.forum_comment_reactions (
  id bigint generated always as identity primary key,
  post_id text not null,
  target_key text not null,
  device_id text not null,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, target_key, device_id)
);

-- RPCs: get_forum_vote_stats(post_id), get_forum_post_reaction_stats(post_id),
--       get_forum_comment_reaction_stats(post_id)
-- See migration file for RLS policies, indexes, and grants.

create table if not exists public.forum_reports (
  id bigint generated always as identity primary key,
  device_id text not null,
  target_key text not null,
  post_id text,
  reason text not null check (reason in ('harassment', 'private', 'self_harm', 'spam', 'other')),
  other_detail text,
  snippet text,
  locale text,
  created_at timestamptz not null default now()
);
-- Full schema + RLS: supabase/migrations/20260517140000_forum_reports.sql
