-- Supabase (Postgres) setup for real "How Others Chose" percentages.
-- Run this in Supabase SQL Editor.

-- 1) Votes table
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  dilemma_id int not null,
  choice text not null check (choice in ('a','b')),
  created_at timestamptz not null default now()
);

-- 2) Enable RLS
alter table public.votes enable row level security;

-- 3) Policy: allow anonymous inserts (for a public voting app)
drop policy if exists "anon insert votes" on public.votes;
create policy "anon insert votes"
on public.votes
for insert
to anon
with check (true);

-- 4) Stats RPC (returns counts for A/B for one dilemma)
-- Marked SECURITY DEFINER so it can read votes even with RLS enabled.
create or replace function public.get_vote_stats(dilemma_id int)
returns table(choice text, count bigint)
language sql
security definer
set search_path = public
as $$
  select v.choice, count(*)::bigint
  from public.votes v
  where v.dilemma_id = get_vote_stats.dilemma_id
  group by v.choice
$$;

revoke all on function public.get_vote_stats(int) from public;
grant execute on function public.get_vote_stats(int) to anon;

-- 5) User feedback (anonymous insert; read in Dashboard / SQL)
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  locale text
);

alter table public.feedback enable row level security;

drop policy if exists "anon insert feedback" on public.feedback;
create policy "anon insert feedback"
on public.feedback
for insert
to anon
with check (true);


-- ============================================================
-- TOMORROW'S FEATURED DILEMMA (community vote)
-- ============================================================
-- Concept:
--   • Users vote for which dilemma_id should be the "featured" card on a FUTURE calendar day.
--   • Rows use target_date = that future day (YYYY-MM-DD in the user's app, local date key).
--   • One vote per device/client_id per target_date (upsert overwrites).
--   • On day D, the app calls get_scheduled_dilemma_for_day(D) which picks the dilemma_id
--     with the highest vote count; ties break by lower dilemma_id.
--
-- How to "calculate" the winner in SQL:
--   SELECT dilemma_id, COUNT(*) AS votes
--   FROM public.tomorrow_dilemma_votes
--   WHERE target_date = '2026-05-04'
--   GROUP BY dilemma_id
--   ORDER BY votes DESC, dilemma_id ASC
--   LIMIT 1;
--
-- The RPC below does this in one call for the client app.
-- ============================================================

create table if not exists public.tomorrow_dilemma_votes (
  target_date date not null,
  dilemma_id int not null check (dilemma_id >= 1 and dilemma_id < 100000),
  voter_client_id text not null check (char_length(voter_client_id) >= 8 and char_length(voter_client_id) <= 128),
  updated_at timestamptz not null default now(),
  primary key (target_date, voter_client_id)
);

create index if not exists tomorrow_dilemma_votes_target_idx on public.tomorrow_dilemma_votes (target_date);
create index if not exists tomorrow_dilemma_votes_target_dilemma_idx on public.tomorrow_dilemma_votes (target_date, dilemma_id);

alter table public.tomorrow_dilemma_votes enable row level security;

-- No direct anon reads/writes; use SECURITY DEFINER functions only.
drop policy if exists "no direct anon" on public.tomorrow_dilemma_votes;
create policy "no direct anon"
on public.tomorrow_dilemma_votes
for all
to anon
using (false)
with check (false);

-- Upsert one vote (anon calls RPC only)
create or replace function public.upsert_tomorrow_dilemma_vote(
  p_target_date date,
  p_dilemma_id int,
  p_voter_client_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tomorrow_dilemma_votes (target_date, dilemma_id, voter_client_id)
  values (p_target_date, p_dilemma_id, p_voter_client_id)
  on conflict (target_date, voter_client_id)
  do update set
    dilemma_id = excluded.dilemma_id,
    updated_at = now();
end;
$$;

revoke all on function public.upsert_tomorrow_dilemma_vote(date, int, text) from public;
grant execute on function public.upsert_tomorrow_dilemma_vote(date, int, text) to anon;

-- Winner for the calendar day the dilemma is SHOWN (target_date = that day)
create or replace function public.get_scheduled_dilemma_for_day(p_show_date date)
returns int
language sql
stable
security definer
set search_path = public
as $$
  with agg as (
    select dilemma_id, count(*)::bigint as c
    from public.tomorrow_dilemma_votes
    where target_date = p_show_date
    group by dilemma_id
  ),
  top as (
    select dilemma_id from agg
    order by c desc, dilemma_id asc
    limit 1
  )
  select dilemma_id from top;
$$;

revoke all on function public.get_scheduled_dilemma_for_day(date) from public;
grant execute on function public.get_scheduled_dilemma_for_day(date) to anon;

-- Optional: full tally for UI (leaderboard for one target day)
create or replace function public.get_tomorrow_vote_stats(p_target_date date)
returns table (dilemma_id int, vote_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select v.dilemma_id, count(*)::bigint
  from public.tomorrow_dilemma_votes v
  where v.target_date = p_target_date
  group by v.dilemma_id
  order by vote_count desc, dilemma_id asc;
$$;

revoke all on function public.get_tomorrow_vote_stats(date) from public;
grant execute on function public.get_tomorrow_vote_stats(date) to anon;

