-- Supabase (Postgres) setup for real "How Others Chose" percentages.
-- Run this in Supabase SQL Editor.

-- 1) Votes table
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  dilemma_id int not null,
  choice text not null check (choice in ('a','b')),
  created_at timestamptz not null default now()
);

-- 2) Enable RLS
alter table public.votes enable row level security;

-- 3) Policy: allow anonymous inserts (for a public voting app)
drop policy if exists "anon insert votes" on public.votes;
create policy "anon insert votes"
on public.votes
for insert
to anon
with check (true);

-- 4) Stats RPC (returns counts for A/B for one dilemma)
-- Marked SECURITY DEFINER so it can read votes even with RLS enabled.
create or replace function public.get_vote_stats(dilemma_id int)
returns table(choice text, count bigint)
language sql
security definer
set search_path = public
as $$
  select v.choice, count(*)::bigint
  from public.votes v
  where v.dilemma_id = get_vote_stats.dilemma_id
  group by v.choice
$$;

revoke all on function public.get_vote_stats(int) from public;
grant execute on function public.get_vote_stats(int) to anon;

-- 5) User feedback (anonymous insert; read in Dashboard / SQL)
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  locale text
);

alter table public.feedback enable row level security;

drop policy if exists "anon insert feedback" on public.feedback;
create policy "anon insert feedback"
on public.feedback
for insert
to anon
with check (true);


-- Removed: "Suggest Tomorrow" / community scheduling
drop function if exists public.upsert_tomorrow_dilemma_vote(date, int, text);
drop function if exists public.get_scheduled_dilemma_for_day(date);
drop function if exists public.get_tomorrow_vote_stats(date);
drop table if exists public.tomorrow_dilemma_votes cascade;
